"""Templates for the daily scheduled service.

These are raw text templates with ``__TOKEN__`` placeholders. The
:mod:`sussed.service` module renders them by replacing each token with a
shell-safe value (see ``str.replace`` usage there). We deliberately avoid
``str.format`` because the shell script body is full of ``${...}`` and
``$(...)`` constructs that would collide with format-field syntax.
"""

from __future__ import annotations

# The prompt handed to `copilot -p`. Real newlines (not literal "\n") so the
# agent receives clean, readable instructions. Embedded in the shell script
# via a quoted heredoc, so no shell interpolation happens.
COPILOT_PROMPT = """Review new sussed apartment listings. Follow these steps exactly:
1. Run: uv run sussed review prepare-batch -n 20 -p apartment --max-age-days 7 --min-quick-score 400 --recent
2. For each prepared JSON in .sussed/image-cache/*-prepared.json, use the sussed-ai-review skill to review it. Dispatch in batches of 5-7 listings with 3-4 parallel agents.
3. Validate each review: uv run sussed review validate <review-path>
4. Save each review: uv run sussed review save <prefix> --input <review-path>
5. After all reviews complete, show the top picks: uv run sussed review picks --min-score 700"""


# The orchestration shell script. Tokens:
#   __PATH_DIRS__      shell-quoted PATH string (colon-joined dirs)
#   __CONFIG_PATH__    shell-quoted absolute config path
#   __PROJECT_DIR__    shell-quoted absolute project dir
#   __UV_BIN__         shell-quoted absolute uv binary path
#   __COPILOT_BIN__    shell-quoted absolute copilot binary path
#   __SCHED_HHMM__     zero-padded HHMM string (e.g. 1000)
#   __COPILOT_PROMPT__ raw prompt text (inserted inside a quoted heredoc)
SHELL_SCRIPT_TEMPLATE = """#!/bin/bash
set -euo pipefail

# Generated by `sussed service install` — DO NOT EDIT.
# Re-run `sussed service install` to regenerate.
#
# SECURITY NOTE: Step 2 runs `copilot` non-interactively over SCRAPED listing
# content, which is untrusted. A malicious listing could attempt prompt
# injection. Permissions are scoped (no --allow-all-urls, so no network/URL
# access) and the working directory is pinned with -C, but only run this
# against real-estate portals you trust.

export PATH=__PATH_DIRS__

SUSSED_DIR="$HOME/.sussed"
LAST_RUN="$SUSSED_DIR/last-run.txt"
LOG_FILE="$SUSSED_DIR/service.log"
RESULTS_DIR="$SUSSED_DIR/results"
LOCK_DIR="$SUSSED_DIR/run.lock"

CONFIG=__CONFIG_PATH__
PROJECT_DIR=__PROJECT_DIR__
UV_BIN=__UV_BIN__
COPILOT_BIN=__COPILOT_BIN__
SCHED_HHMM=__SCHED_HHMM__

mkdir -p "$SUSSED_DIR" "$RESULTS_DIR"
chmod 700 "$SUSSED_DIR" 2>/dev/null || true

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

notify() {
    # $1=title  $2=subtitle  $3=message
    if [[ "$(uname)" == "Darwin" ]]; then
        /usr/bin/osascript - "$1" "$2" "$3" >/dev/null 2>&1 <<'APPLESCRIPT' || true
on run argv
    display notification (item 3 of argv) with title (item 1 of argv) subtitle (item 2 of argv)
end run
APPLESCRIPT
    elif command -v notify-send >/dev/null 2>&1; then
        notify-send "$1" "$2 — $3" >/dev/null 2>&1 || true
    else
        log "notify-send not available; skipping desktop notification"
    fi
}

# --- Concurrency lock (atomic mkdir) ---
if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    log "Another run is in progress (lock: $LOCK_DIR); exiting."
    exit 0
fi
trap 'rmdir "$LOCK_DIR" 2>/dev/null || true' EXIT

# --- Run guard: skip if already ran today ---
TODAY=$(date +%Y-%m-%d)
if [[ -f "$LAST_RUN" && "$(cat "$LAST_RUN" 2>/dev/null)" == "$TODAY" ]]; then
    log "Already ran today ($TODAY); skipping."
    exit 0
fi

# --- Schedule guard: don't run before the scheduled time ---
# Stops a login-time (RunAtLoad) trigger from running early and consuming the
# day's run. The calendar/timer trigger fires exactly at SCHED_HHMM; a later
# boot (machine was off at the scheduled time) still catches up because NOW
# will be >= SCHED_HHMM.
NOW_HHMM=$(date +%H%M)
if (( 10#$NOW_HHMM < 10#$SCHED_HHMM )); then
    log "Before scheduled time ($SCHED_HHMM); waiting for the scheduled trigger."
    exit 0
fi

START_TIME=$(date +%s)
log "=== sussed daily run starting ==="

# Step 1: Hunt with scrape
log "Step 1: sussed hunt --scrape ..."
cd "$PROJECT_DIR"
if "$UV_BIN" run sussed hunt --scrape -c "$CONFIG" 2>&1 | tee -a "$LOG_FILE"; then
    log "Step 1 complete."
else
    log "Step 1 FAILED."
    notify "sussed ⚠️" "Hunt failed" "Check ${LOG_FILE/#$HOME/~}"
    exit 1
fi

# Step 2: AI review via Copilot CLI (scoped perms, no network access)
log "Step 2: Copilot AI review ..."
PROMPT=$(cat <<'PROMPT_EOF'
__COPILOT_PROMPT__
PROMPT_EOF
)
if "$COPILOT_BIN" -p "$PROMPT" --allow-all-tools --allow-all-paths --no-ask-user -C "$PROJECT_DIR" 2>&1 | tee -a "$LOG_FILE"; then
    log "Step 2 complete."
else
    log "Step 2 FAILED; generating report from existing reviews."
fi

# Step 3: Daily report
log "Step 3: generating report ..."
REPORT="$RESULTS_DIR/$TODAY-daily-report.md"
PICKS_JSON=$("$UV_BIN" run sussed review picks --min-score 700 -f json --max-age-days 7 2>/dev/null || echo "[]")
END_TIME=$(date +%s)
DURATION=$(( END_TIME - START_TIME ))
GEM_COUNT=$( { printf '%s' "$PICKS_JSON" | grep -o '"score"' || true; } | wc -l | tr -d ' ')

{
    printf '# sussed Daily Report — %s\\n\\n' "$TODAY"
    printf '**Run:** %s | **Duration:** %sm %ss\\n' "$(date '+%H:%M:%S')" "$((DURATION / 60))" "$((DURATION % 60))"
    printf '**Config:** %s\\n' "$CONFIG"
    printf '**Picks (score >= 700):** %s\\n\\n' "$GEM_COUNT"
    printf '## Top Picks\\n\\n'
    printf '```json\\n'
    printf '%s\\n' "$PICKS_JSON"
    printf '```\\n\\n'
    printf 'Full log: %s\\n' "$LOG_FILE"
} > "$REPORT"

echo "$TODAY" > "$LAST_RUN"
REPORT_SHORT="${REPORT/#$HOME/~}"
log "=== complete ($((DURATION / 60))m $((DURATION % 60))s) — report: $REPORT ==="
notify "sussed 🏠" "Daily hunt complete" "$GEM_COUNT picks found — see $REPORT_SHORT"
"""


# systemd user service. Tokens: none (uses %h for home). The timer enables the
# job, so this unit has NO [Install] section.
SYSTEMD_SERVICE_TEMPLATE = """[Unit]
Description=sussed daily apartment hunt and AI review
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/bin/bash %h/.sussed/sussed-daily.sh
"""


# systemd user timer. Tokens: __HHMM_HOUR__, __HHMM_MINUTE__ (zero-padded).
SYSTEMD_TIMER_TEMPLATE = """[Unit]
Description=sussed daily hunt + review timer

[Timer]
OnCalendar=*-*-* __HHMM_HOUR__:__HHMM_MINUTE__:00
Persistent=true

[Install]
WantedBy=timers.target
"""


# launchd agent. Tokens: __HOME__, __HHMM_HOUR__, __HHMM_MINUTE__.
# stdout/stderr go to a SEPARATE launchd.log so early crashes are captured
# without duplicating the script's own `tee`-based service.log lines.
LAUNCHD_PLIST_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.sussed.daily</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>__HOME__/.sussed/sussed-daily.sh</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>__HHMM_HOUR__</integer>
        <key>Minute</key>
        <integer>__HHMM_MINUTE__</integer>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>__HOME__/.sussed/launchd.log</string>
    <key>StandardErrorPath</key>
    <string>__HOME__/.sussed/launchd.log</string>
</dict>
</plist>
"""
